apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: web
        image: app:latest
        imagePullPolicy: Never # side-load via minikube
        ports:
        - containerPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    component: web
spec:
  selector:
    component: web
  ports:
    - protocol: TCP
      port: 2112
