apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    component: db
    {{- include "tryingout.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: db
      {{- include "tryingout.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: db
        {{- include "tryingout.labels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: postgres:13.1-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "trying_out_production"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    component: db
    {{- include "tryingout.labels" . | nindent 4 }}
spec:
  selector:
    component: db
    {{- include "tryingout.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5432
