---
development:
  dialect: postgres
  database: trying_out_production
  user: postgres
  password: postgres
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/trying_out_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/trying_out_production?sslmode=disable"}}
